### ISSUE TITLE
SBML is incomplete when .* is used instead of *

### ISSUE THREAD

**Issue by willigott** [sbmlteam/moccasin#51]
First of all, thanks for this package, this will be of great help.

I ran into an issue, however. Taking the example from the readme

```
tspan  = [0 300];
xinit  = [0; 0];
a      = 0.01 * 60;
b      = 0.0058 * 60;
c      = 0.006 * 60;
d      = 0.000192 * 60;

% A call to a MATLAB ODE solver
[t, x] = ode45(@f, tspan, xinit);

% A function that defines the ODEs of the model.
function dx = f(t, x)
  dx = [a - b * x(1); c * x(1) - d * x(2)];
end
```
That works perfectly fine. However, I currently deal with a file where each `*` is written as `.*` (although there are no vectors/matrices involved). Then it gives an incomplete output. For the example above, if one uses (note the dots)

`dx = [a - b .* x(1); c .* x(1) - d .* x(2)];`

one will obtain an incomplete SBML (`x2` is missing and so are the reactions):

```
------------------------- Reaction-based SBML output -------------------------

<?xml version="1.0" encoding="UTF-8"?>
<!-- Created by MOCCASIN version 1.1.0 on 2018-05-04 15:32 with libSBML version 5.16.0. -->
<sbml xmlns="http://www.sbml.org/sbml/level3/version1/core" level="3" version="1">
  <model id="Model_generated_by_BIOCHAM">
    <listOfCompartments>
      <compartment id="compartmentOne" spatialDimensions="3" size="1" constant="true"/>
    </listOfCompartments>
    <listOfSpecies>
      <species id="x_1" name="x_1" compartment="compartmentOne" initialConcentration="0" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
    </listOfSpecies>
    <listOfParameters>
      <parameter id="a" name="a" value="0" constant="true"/>
      <parameter id="b" name="b" value="0" constant="true"/>
      <parameter id="c" name="c" value="0" constant="true"/>
      <parameter id="d" name="d" value="0" constant="true"/>
    </listOfParameters>
    <listOfInitialAssignments>
      <initialAssignment symbol="a">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <cn> 0.01 </cn>
            <cn type="integer"> 60 </cn>
          </apply>
        </math>
      </initialAssignment>
      <initialAssignment symbol="b">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <cn> 0.0058 </cn>
            <cn type="integer"> 60 </cn>
          </apply>
        </math>
      </initialAssignment>
      <initialAssignment symbol="c">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <cn> 0.006 </cn>
            <cn type="integer"> 60 </cn>
          </apply>
        </math>
      </initialAssignment>
      <initialAssignment symbol="d">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <cn> 0.000192 </cn>
            <cn type="integer"> 60 </cn>
          </apply>
        </math>
      </initialAssignment>
    </listOfInitialAssignments>
  </model>
</sbml>
```

I struggle a bit to find other limitations (I fixed this issue, also for `.^` and `./` but still the model is not converted correctly), so are there any general guidelines on how the rates have to be defined in order to be parsed correctly?

**Comment by mhucka** [comment]
Thank you for reporting this bug. This was an important bug report. It revealed more than one problem:

1. The code that checked whether a given input is translatable was never even called, which means that many MATLAB inputs were never even checked as being things that MOCCASIN can translate.
2. The presence of the particular class of operators used here (such as `.*`) never got tested, and since these operators cannot be translated, later stages of the conversion process basically garbled the input silently. This is what led to the particular result here of bad XML output.
3. Users may employ some matrix operators in their input (such as `.*`) but not actually use them in a matrix sense. MOCCASIN could translate them in that case, if it knew that array-wise actions were not actually being employed. There may be a way that MOCCASIN would infer this automatically, but right now I can't think of a safe way to do it. However, it _would_ be possible to let the user tell MOCCASIN to assume it can treat the operators as their non-matrix equivalents.
4. There is insufficient documentation about what can and cannot be translated, so users don't know.

I'm working on fixes for items 1–3 currently and hope to have that done shortly. Item 4 needs documentation somewhere and I'll try to work on that soon. (Our apologies for the poor documentation. The short answer is that matrix operations can't be translated, nor most MATLAB constructs aside from the basic things you see in the examples.)

**Comment by mhucka** [comment]
In branch [wip-release-1.2](https://github.com/sbmlteam/moccasin/tree/wip-release-1.2), the code now attempts to check for these constructs and complains if it finds them. There are additional flags and checkboxes now to tell MOCCASIN to go ahead and translate the element-wise operators to regular operators. (Flag `-r` on the command line, and a checkbox in the GUI.) It needs more testing and a full release to be done, but it's available from the branch you are interested in trying it out.

I hope to get the release done this week.
